let postList = [ "intro",
    "oque",
    "software",
    "gabinete",
    "processador",
    "placamae",
    "discorigido",
    "memoriaram",
    "umpouco",
    "oconceito",
    "areatrabalho",
    "mouse",
    "barratarefas",
    "configuracoes",
    "explorador",
    "teclado",
    "unidades",
    "acessorios",
    "manipulando",
    "msedge",
    "pesquisa",
    "downloadarquivos",
    "downloadapps",
    "google",
    "msaccount",
    "sitesuteis",
    "cachecookies",
    "msword",
    "mspowerpoint",
    "msexcel",
    "mspublisher",
    "esteja",
    "senhas",
    "nuvem",
    "instalacao",
    "msdefender",
    "taskmgr",
    "saude",
    "limpezadisco",
    "verdisco",
    "verarquivos",
    "seguranca",
    "restauracao",
    "raiz",
    "log",
    "servicos",
    "drivers",
    "agendador",
    "diskmgmt",
    "powershell",
    "rede",
    "proximos",
    "dev",
    "design",
    "opensource",
    "oautor"
];
let post = 0;
let postCount = 0;
function navigateTo(index) {
    if (index >= 0 && index <= postCount) {
        post = index;
        window.location = `https://www.jorgesouza.com.br/informatica/${postList[index]}`;
    }
}

